title: Abhishek Sinha # your name (or website title) here
logo: "/images/Profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Manager,leading AI solutioning & E2E delivery for clients on choice of their cloud (AWS/Azure/GCP). 
  More than 7 years of experience in building Data & Analytics pipelines. 
  Around 6 years of experience on building & delivering ML and MLOps solutions.
  <br><br>
  Currently working on new trends:
  - Sustainable AI
  - Industry 4.0
  - Industrial IoT Pipelines from OT to IT
  - Graph Data Science
  - Foundation Models
  <br><br>
  <a href="https://www.linkedin.com/in/abhisheksinha0987/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
